---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  when: nginx_yum_repo_enabled

- name: Ensure nginx is installed.
  yum:
    name: "{{ nginx_package_name }}"
    state: installed

- name: Insert firewalld rules for tcp ports
  firewalld: port="{{ item }}/tcp" permanent=true state=enabled immediate=yes
  when: tcp_ports is defined
  with_items: "{{ tcp_ports }}"

- name: Selinux - enable tcp stream for nginx tcp streams
  when: tcp_streams is defined
  seport: port={{ item }} proto=tcp setype=http_port_t state=present
  when: tcp_ports is defined
  with_items: "{{ tcp_ports }}"

- name: Insert firewalld rules for tcp stream ports
  firewalld: port="{{ item.listen_port  }}/tcp" permanent=true state=enabled immediate=yes
  with_items: "{{ tcp_streams }}"

- name: Selinux - enable tcp stream ports for nginx tcp streams
  when: tcp_streams is defined
  seport: ports={{ item.listen_port }} proto=tcp setype=http_port_t state=present
  with_items: "{{ tcp_streams }}"

